success:
  200ok:
    code: 20000000
    desc: 정상 처리 되었습니다.
    status: 200
# code - 맨 앞 3자리: status, 4번째 수: 시스템정의(0)/사용자정의(1), 맨 뒤 4자리: 메시지 식별번호
exception:
  com.fasterxml.jackson.core.io.JsonEOFException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  com.fasterxml.jackson.core.JsonParseException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  com.fasterxml.jackson.databind.exc.MismatchedInputException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  com.fasterxml.jackson.databind.JsonMappingException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  com.fasterxml.jackson.databind.exc.InvalidDefinitionException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  org.springframework.http.converter.HttpMessageConversionException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  org.springframework.http.converter.HttpMessageNotReadableException:
    code: 40000001
    desc: JSON 변환 중 문제가 있습니다.
    status: 400
  parameter.validation.error:
    code: 40000011
    desc: 입력값 오류 입니다.
    status: 400
  org.springframework.validation.BindException:
    code: 40000011
    desc: 입력값 오류 입니다.
    status: 400
  parameter.validation.IllegalArgumentException:
    code: 40000011
    desc: 입력값 오류 입니다.
    status: 400
  java.lang.IllegalArgumentException:
    code: 40000011
    desc: 입력값 오류 입니다.
    status: 400
  org.springframework.web.bind.MethodArgumentNotValidException:
    code: 40000012
    desc: 입력값 오류 입니다.
    status: 400
  org.springframework.data.mapping.PropertyReferenceException:
    code: 40000101
    desc: 올바른 키워드가 아닙니다.
    status: 400
  org.springframework.security.authentication.BadCredentialsException:
    code: 40100001
    desc: 아이디 또는 비밀번호가 일치하지않습니다.
    status: 401
  org.springframework.security.authentication.DisabledException:
    code: 40100002
    desc: 유효하지 않은 사용자입니다.
    status: 401
  org.springframework.security.access.AccessDeniedException:
    code: 40300001
    desc: 접근이 거부되었습니다.
    status: 403
  org.springframework.web.servlet.NoHandlerFoundException:
    code: 40400001
    desc: 지원하지 않는 URL
    status: 404
  org.springframework.web.HttpRequestMethodNotSupportedException:
    code: 40500001
    desc: 잘못된 요청입니다.
    status: 405
  org.springframework.web.multipart.MaxUploadSizeExceededException:
    code: 50000001
    desc: 파일 크기가 10MB를 초과했습니다.
    status: 500
  org.springframework.jdbc:
    code: 50000011
    desc: 데이터베이스 오류
    status: 500
  org.apache.ibatis.reflection.ReflectionException:
    code: 50000011
    desc: 데이터베이스 오류
    status: 500
  org.springframework.dao.DataAccessException:
    code: 50000012
    desc: 데이터베이스 오류
    status: 500
  org.apache.ibatis.javassist.NotFoundException:
    code: 50000012
    desc: 데이터베이스 오류
    status: 500
  org.springframework.dao.DataIntegrityViolationException:
    code: 50000013
    desc: 데이터베이스 오류(외래키 참조 조건)
    status: 500
  java.sql.SQLException:
    code: 50000014
    desc: 데이터 베이스 SQL 에러.
    status: 500
  org.springframework.jdbc.BadSqlGrammarException:
    code: 50000015
    desc: 데이터베이스 오류({0})
    status: 500
  java.lang.ArithmeticException:
    code: 50000015
    desc: 데이터베이스 오류({0})
    status: 500
  org.springframework.dao.DuplicateKeyException:
    code: 50000031
    desc: 중복된 값이 존재합니다.
    status: 500
  java.security.NoSuchAlgorithmException:
    code: 50000041
    desc: 해시 변환 오류
    status: 500
  invalid:
    code: 40010001
    desc: '입력값 오류 입니다.'
    status: 400
  already_exists:
    code: 40010002
    desc: '이미 존재하는 데이터 입니다.'
    status: 400
  not_exists:
    code: 40010003
    desc: '존재하지않는 데이터 입니다.'
    status: 400
  unauthorized:
    code: 40110021
    desc: '로그인이 필요합니다.'
    status: 401
  expired_jwt:
    code: 40110022
    desc: '만료된 토큰입니다.'
    status: 401
  invalid_jwt:
    code: 40110023
    desc: '유효하지않은 토큰입니다.'
    status: 401
  invalid_refresh_token:
    code: 40110024
    desc: '유효하지않은 토큰입니다.'
    status: 401
  expired_refresh_token:
    code: 40110025
    desc: '만료된 토큰입니다.'
    status: 401
  disabled_account:
    code: 40110026
    desc: '사용 불가능한 계정입니다.'
    status: 401
  forbidden:
    code: 40310001
    desc: '이 페이지를 볼 수 있는 권한이 없습니다.'
    status: 403
  not_define:
    code: 50019999
    desc: '정의되지않은 오류입니다 '
    status: 500
# --- 여기까지가 공통 부분 ---
  password_confirm:
    code: 40011001
    desc: '비밀번호 확인 값이 일치하지 않습니다.'
    status: 400
  already_exists_email:
    code: 40011002
    desc: '이미 존재하는 이메일 입니다.'
    status: 400
