pet-diary-membership:
  master:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/pet_diary_membership
      username: root
      password: P@ssw0rd
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5
  slave:
    datasource:
      enabled: true
      jdbc-url: jdbc:mysql://localhost:3306/pet_diary_membership
      username: root
      password: P@ssw0rd
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5

redis:
  pet-diary:
    host: 127.0.0.1
    port: 6379
    password: 1q2w3e4r5t@#
    use-tls: false

spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
  devtools:
    livereload:
      enabled: true
      port: 35730

logging:
  level:
    com.petdiary: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace

cors:
  allowed-credentials: true
  allowed-header: "*"
  allowed-method: "*"
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080

auth:
  jwt:
    secret: 2bf0bacbc66ce8638bfbc35d5541e20df0acf33a0bf3c6ca75dc146b1dcfbbc636db30003674bca49b49026dfa37aad315d7ec314436c867841536a9ce18bcf3
