server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /

spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        show-sql: false
        jdbc:
          batch_size: 500
        batch_fetch_style: dynamic
        default_batch_fetch_size: 100
        hbm2ddl:
          auto: none
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    livereload:
      enabled: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(Hd6fV7EhSPupRfxU9g+gnFyoE/pJHK5Tvffli2T35EyWr1a1B30OACE/X8MksRg7)
            client-secret: ENC(ImcTPyS2huuVo4ieOBmrHjeYKVZra5APW6Azg8G1cwreyqeZdDfsC7kCiGiyP/Jc)
            redirect-uri: "{baseUrl}/oauth2/code/{registrationId}" # http://localhost:8080/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

auth:
  jwt:
    expiry-in-ms: 3600000
    refresh-expiry-in-days: 30
    type: Bearer
    secret: ENC(ybNUuE0/DwL2sRonHAa610O6bUcJ7RL/TEmo+ejzRCb1uDmZiiHfey2byytCua9HP3fSp0dnpuJp5nLGI6aawQONJ6nywyptXEUVUxPOfbai7xQqT+Ld38tWVVhBLdsSDh6lN6pS1qwajP+fMC+7yNioknbEqKKkp063Xiaxoc2epBnvnsQfexMcpXcpWw5w)


management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,info,health
  prometheus:
    metrics:
      export:
        enabled: true
