{
 "title": "ToyProject: PetDiary - Auth API Server",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "JVM 메모리 사용량(MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes / (1024 * 1024)",
     "legendFormat": "{{area}}:{{id}}"
    }
   ]
  },
  {
   "title": "URI 요청 횟수 통계",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!~\"/actuator/prometheus|/swagger-ui.html|/static/.*\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "시스템 CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "데이터베이스 요청 응답 시간 통계",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_sum/spring_data_repository_invocations_seconds_count",
     "legendFormat": "{{repository}}:{{state}}"
    }
   ]
  },
  {
   "title": "메소드 실행 시간",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, method_execution_time_seconds_sum / method_execution_time_seconds_count)",
     "legendFormat": "{{class}}:{{method}}"
    }
   ]
  }
 ]
}