
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/pet_diary
    username: petdiaryuser
    password: 1q2w3e4r5t@#
    driver-class-name: com.mysql.cj.jdbc.Driver
