pet-diary:
  master:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/pet_diary
      username: root
      password: P@ssw0rd
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5
  slave:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/pet_diary
      username: root
      password: P@ssw0rd
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5

spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
  devtools:
    livereload:
      enabled: true
      port: 35730

logging:
  level:
    com.petdiary: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace

cors:
  allowed-credentials: true
  allowed-header: "*"
  allowed-method: "*"
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080

pet-diary-auth-client:
  base-url: http://localhost:8081
  token-type: Bearer
