pet-diary:
  master:
    datasource:
      jdbc-url: ENC(ZI3IlHa5kSiwK3+xButTNcJucq1ldaluGpajbVhQc3f6Lb84BUCG2m6ZMyrd+GKmE96byAsZ1NMHKyrgQyzK63FSzO6AnKhLYnli82LlSwmhwBXqcpzuLVyYgPzlr+grWSVrVMAt3Yc=)
      username: ENC(3083ya/0xJD1IBT8LFFLNtLMQjgqQmei)
      password: ENC(CRcm0n/2tjTa+TFt0acXev3dPIgvTcE8)
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5
  slave:
    datasource:
      jdbc-url: ENC(ZI3IlHa5kSiwK3+xButTNcJucq1ldaluGpajbVhQc3f6Lb84BUCG2m6ZMyrd+GKmE96byAsZ1NMHKyrgQyzK63FSzO6AnKhLYnli82LlSwmhwBXqcpzuLVyYgPzlr+grWSVrVMAt3Yc=)
      username: ENC(3083ya/0xJD1IBT8LFFLNtLMQjgqQmei)
      password: ENC(CRcm0n/2tjTa+TFt0acXev3dPIgvTcE8)
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5

spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
  devtools:
    livereload:
      enabled: true
      port: 35730

logging:
  level:
    com.petdiary: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace


cors:
  allowed-credentials: true
  allowed-header: "*"
  allowed-method: "*"
  allowed-origins:
    - https://kjb4494.site
    - https://www.kjb4494.site
    - https://swagger.kjb4494.site
